# Generated by Django 6.0.3 on 2026-03-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record26SpDbA2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=8)),
                ('similarity', models.FloatField(null=True)),
                ('latency', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '[26SpDbA2]Record',
                'verbose_name_plural': '[26SpDbA2]Records',
            },
        ),
    ]
