# Generated by Django 6.0.3 on 2026-03-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record26spdba2',
            name='latency',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record26spdba2',
            name='similarity',
            field=models.IntegerField(null=True),
        ),
    ]
