# Generated by Django 6.0.3 on 2026-04-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_record26spdba2_latency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record26SpDbA3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=8)),
                ('score', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '[26SpDbA3]Record',
                'verbose_name_plural': '[26SpDbA3]Records',
            },
        ),
    ]
